input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/34d11af69e22/_beeline_runtime/genie3/inputs"
  datasets:
    - dataset_id: "34d11af69e22"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
  algorithms:
    - algorithm_id: "GENIE3"
      image: "grnbeeline/arboreto:base"
      should_run: [True]
      params:
        {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/34d11af69e22/_beeline_runtime/genie3/outputs"
