input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/fa8e5bfb7d52/_beeline_runtime/GRNBOOST2/inputs"
  datasets:
    - dataset_id: "fa8e5bfb7d52"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
        - run_id: "run-2"
          exprData: "ExpressionData.csv"
        - run_id: "run-3"
          exprData: "ExpressionData.csv"
        - run_id: "run-4"
          exprData: "ExpressionData.csv"
        - run_id: "run-5"
          exprData: "ExpressionData.csv"
        - run_id: "run-6"
          exprData: "ExpressionData.csv"
        - run_id: "run-7"
          exprData: "ExpressionData.csv"
        - run_id: "run-8"
          exprData: "ExpressionData.csv"
        - run_id: "run-9"
          exprData: "ExpressionData.csv"
        - run_id: "run-10"
          exprData: "ExpressionData.csv"
        - run_id: "run-11"
          exprData: "ExpressionData.csv"
        - run_id: "run-12"
          exprData: "ExpressionData.csv"
        - run_id: "run-13"
          exprData: "ExpressionData.csv"
        - run_id: "run-14"
          exprData: "ExpressionData.csv"
        - run_id: "run-15"
          exprData: "ExpressionData.csv"
        - run_id: "run-16"
          exprData: "ExpressionData.csv"
        - run_id: "run-17"
          exprData: "ExpressionData.csv"
        - run_id: "run-18"
          exprData: "ExpressionData.csv"
        - run_id: "run-19"
          exprData: "ExpressionData.csv"
        - run_id: "run-20"
          exprData: "ExpressionData.csv"
        - run_id: "run-21"
          exprData: "ExpressionData.csv"
        - run_id: "run-22"
          exprData: "ExpressionData.csv"
        - run_id: "run-23"
          exprData: "ExpressionData.csv"
        - run_id: "run-24"
          exprData: "ExpressionData.csv"
        - run_id: "run-25"
          exprData: "ExpressionData.csv"
        - run_id: "run-26"
          exprData: "ExpressionData.csv"
        - run_id: "run-27"
          exprData: "ExpressionData.csv"
        - run_id: "run-28"
          exprData: "ExpressionData.csv"
        - run_id: "run-29"
          exprData: "ExpressionData.csv"
        - run_id: "run-30"
          exprData: "ExpressionData.csv"
  algorithms:
    - algorithm_id: "GRNBOOST2"
      image: "grnbeeline/arboreto:base"
      should_run: [True]
      params:
        {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/fa8e5bfb7d52/_beeline_runtime/GRNBOOST2/outputs"
