input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/68e4421f160b/_beeline_runtime/pidc/inputs"
  datasets:
    - dataset_id: "68e4421f160b"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
  algorithms:
    - algorithm_id: "PIDC"
      image: "grnbeeline/pidc:base"
      should_run: [True]
      params:
        {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/68e4421f160b/_beeline_runtime/pidc/outputs"
