input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/663be6e7c36d/_beeline_runtime/ppcor/inputs"
  datasets:
    - dataset_id: "663be6e7c36d"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
  algorithms:
    - algorithm_id: "PPCOR"
      image: "grnbeeline/ppcor:base"
      should_run: [True]
      params: {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/663be6e7c36d/_beeline_runtime/ppcor/outputs"
