input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/048e97097ddd/_beeline_runtime/PPCOR/inputs"
  datasets:
    - dataset_id: "048e97097ddd"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
          pseudoTimeData: "PseudoTime.csv"
  algorithms:
    - algorithm_id: "PPCOR"
      image: "grnbeeline/ppcor:base"
      should_run: [True]
      params:
        pVal: [0.01]
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/048e97097ddd/_beeline_runtime/PPCOR/outputs"
