import { Algorithm } from "../_types/algorithm";

export const algorithms: Algorithm[] = [
  {
    id: "genie3",
    name: "GENIE3",
    description: "Tree-based GRN inference method that predicts regulators for each target gene.",
    category: "Random forest",
    year: "2010",
    journal: "PLoS One",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "grnboost2",
    name: "GRNBoost2",
    description: "Gradient-boosting based GRN inference method designed as a faster tree-based alternative.",
    category: "Random forest",
    year: "2018",
    journal: "Bioinformatics",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "pidc",
    name: "PIDC",
    description: "Information-theoretic method that infers gene relationships using multivariate mutual-information ideas.",
    category: "Mutual information",
    year: "2017",
    journal: "Cell Systems",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: false,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "ppcor",
    name: "PPCOR",
    description: "Partial-correlation method that estimates direct linear associations between genes.",
    category: "Correlation",
    year: "2015",
    journal: "Communications for Statistical Applications and Methods",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: false,
    signed: true,
    requiresPseudotime: false,
  },
  {
    id: "pearson",
    name: "Pearson Correlation",
    description: "Simple Pearson-correlation baseline for measuring pairwise co-expression.",
    category: "Correlation",
    year: "—",
    journal: "—",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: false,
    signed: true,
    requiresPseudotime: false,
  },
  {
    id: "grnvbem",
    name: "GRNVBEM",
    description:
      "Variational Bayesian regression method for ordered cells that outputs directed signed edges.",
    category: "Regression",
    year: "2018",
    journal: "Bioinformatics",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "jump3",
    name: "JUMP3",
    description:
      "Tree-based method for ordered-cell gene regulatory network inference.",
    category: "Machine Learning",
    year: "2015",
    journal: "Bioinformatics",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "leap",
    name: "LEAP",
    description:
      "Lag-based correlation method that uses ordered cells to suggest directed relationships.",
    category: "Correlation",
    year: "2017",
    journal: "Bioinformatics",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "scode",
    name: "SCODE",
    description:
      "Ordinary-differential-equation based method for ordered cells that produces directed signed edges.",
    category: "ODE + regression",
    year: "2017",
    journal: "Bioinformatics",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "scribe",
    name: "SCRIBE",
    description:
      "Directed-information based method for ordered cells that infers directed regulatory links.",
    category: "Mutual information",
    year: "2018",
    journal: "bioRxiv preprint",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "sincerities",
    name: "SINCERITIES",
    description:
      "Regression-based method for ordered cells that outputs directed signed edges.",
    category: "Regression",
    year: "2018",
    journal: "Bioinformatics",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "singe",
    name: "SINGE",
    description:
      "Granger-causality based method for ordered cells that predicts directed relationships.",
    category: "Granger causality",
    year: "2019",
    journal: "bioRxiv preprint",
    runtime: "TBD",
    runtimeMinutes: 0,
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
];

export const recommendedIds = ["pidc", "genie3", "grnboost2"];