import { Algorithm } from "../_types/algorithm";

export const algorithms: Algorithm[] = [
  {
    id: "PIDC",
    name: "PIDC",
    description: "Information-theory method for undirected GRN inference.",
    category: "Mutual information",
    year: "2017",
    journal: "Cell Systems",
    directed: false,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "GENIE3",
    name: "GENIE3",
    description: "Tree-based method for predicting regulators of target genes.",
    category: "Random forest",
    year: "2010",
    journal: "PLoS One",
    directed: true,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "GRNBOOST2",
    name: "GRNBoost2",
    description: "Fast tree-based alternative to GENIE3.",
    category: "Random forest",
    year: "2018",
    journal: "Bioinformatics",
    directed: true,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "PPCOR",
    name: "PPCOR",
    description: "Partial-correlation method for signed gene associations.",
    category: "Correlation",
    year: "2015",
    journal: "Communications for Statistical Applications and Methods",
    directed: false,
    signed: true,
    requiresPseudotime: false,
  },
  {
    id: "SCODE",
    name: "SCODE",
    description: "ODE-based method for ordered single-cell data.",
    category: "ODE + regression",
    year: "2017",
    journal: "Bioinformatics",
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "SINCERITIES",
    name: "SINCERITIES",
    description: "Regression method for time-ordered expression data.",
    category: "Regression",
    year: "2018",
    journal: "Bioinformatics",
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "SCRIBE",
    name: "SCRIBE",
    description: "Information-theory method for directed regulatory links.",
    category: "Mutual information",
    year: "2018",
    journal: "bioRxiv preprint",
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "SINGE",
    name: "SINGE",
    description: "Granger-causality method for ordered single-cell data.",
    category: "Granger causality",
    year: "2019",
    journal: "bioRxiv preprint",
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "LEAP",
    name: "LEAP",
    description: "Lagged-correlation method using pseudotime ordering.",
    category: "Correlation",
    year: "2017",
    journal: "Bioinformatics",
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "GRISLI",
    name: "GRISLI",
    description: "ODE-regression method for ordered single-cell data.",
    category: "ODE + regression",
    year: "2018",
    journal: "bioRxiv preprint",
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "GRNVBEM",
    name: "GRNVBEM",
    description: "Variational Bayesian method for directed signed GRNs.",
    category: "Regression",
    year: "2018",
    journal: "Bioinformatics",
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "SCNS",
    name: "SCNS",
    description: "Boolean-model method for time-course single-cell data.",
    category: "Boolean model",
    year: "2018",
    journal: "BMC Systems Biology",
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
];

export const recommendedIds = ["PIDC", "GENIE3", "GRNBOOST2"];