import { Algorithm } from "../_types/algorithm";

export const algorithms: Algorithm[] = [
  {
    id: "genie3",
    name: "GENIE3",
    description: "Tree-based ensemble method for ranking regulatory links.",
    category: "Machine Learning",
    year: "2010",
    journal: "PLoS ONE",
    runtime: "~ 25 min",
    runtimeMinutes: 25,
    directed: true,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "grnboost2",
    name: "GRNBoost2",
    description:
      "Gradient-boosting approach optimized for scalable GRN inference.",
    category: "Machine Learning",
    year: "2019",
    journal: "Cell Systems",
    runtime: "~ 10 min",
    runtimeMinutes: 10,
    directed: true,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "pidc",
    name: "PIDC",
    description:
      "Information-theoretic inference using partial information decomposition.",
    category: "Information Theory",
    year: "2017",
    journal: "Bioinformatics",
    runtime: "~ 8 min",
    runtimeMinutes: 8,
    directed: true,
    signed: false,
    requiresPseudotime: false,
  },
  {
    id: "ppcor",
    name: "PPCOR",
    description:
      "Partial correlation method for estimating direct linear dependencies.",
    category: "Correlation",
    year: "2015",
    journal: "Statistical Method",
    runtime: "~ 4 min",
    runtimeMinutes: 4,
    directed: false,
    signed: true,
    requiresPseudotime: false,
  },
  {
    id: "pearson",
    name: "Pearson Correlation",
    description:
      "Correlation-based baseline for fast co-expression discovery.",
    category: "Correlation",
    year: "Classic",
    journal: "Statistical Method",
    runtime: "~ 2 min",
    runtimeMinutes: 2,
    directed: false,
    signed: true,
    requiresPseudotime: false,
  },
  {
    id: "grnvbem",
    name: "GRNVBEM",
    description:
      "Variational Bayesian expectation-maximization for sparse GRN inference.",
    category: "Bayesian",
    year: "2018",
    journal: "Bioinformatics",
    runtime: "~ 18 min",
    runtimeMinutes: 18,
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "jump3",
    name: "JUMP3",
    description:
      "Tree-based time-aware GRN method designed for snapshot and dynamic data.",
    category: "Machine Learning",
    year: "2019",
    journal: "BMC Bioinformatics",
    runtime: "~ 28 min",
    runtimeMinutes: 28,
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
  {
    id: "leap",
    name: "LEAP",
    description:
      "Lag-based correlation method that uses pseudotime ordering to infer regulation.",
    category: "Correlation",
    year: "2017",
    journal: "Nature Communications",
    runtime: "~ 14 min",
    runtimeMinutes: 14,
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "scode",
    name: "SCODE",
    description:
      "Ordinary differential equation model for efficient pseudotime-based GRN reconstruction.",
    category: "ODE",
    year: "2016",
    journal: "Bioinformatics",
    runtime: "~ 12 min",
    runtimeMinutes: 12,
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "scribe",
    name: "SCRIBE",
    description:
      "Information-based causal inference over dynamic cell trajectories.",
    category: "Information Theory",
    year: "2018",
    journal: "PNAS",
    runtime: "~ 30 min",
    runtimeMinutes: 30,
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "sincerities",
    name: "SINCERITIES",
    description:
      "Time-stamped regularized regression framework for dynamic GRN inference.",
    category: "Regression",
    year: "2018",
    journal: "Bioinformatics",
    runtime: "~ 20 min",
    runtimeMinutes: 20,
    directed: true,
    signed: true,
    requiresPseudotime: true,
  },
  {
    id: "singe",
    name: "SINGE",
    description:
      "Granger-causality framework that uses pseudotime-ordered cells.",
    category: "Granger Causality",
    year: "2019",
    journal: "Cell Systems",
    runtime: "~ 35 min",
    runtimeMinutes: 35,
    directed: true,
    signed: false,
    requiresPseudotime: true,
  },
];

export const recommendedIds = ["pidc", "genie3", "grnboost2"];