export function getNetworkGraphStylesheet() {
  return [
    {
      selector: "node",
      style: {
        label: "data(label)",
        color: "#ffffff",
        "font-family": "Arial, Helvetica, sans-serif",
        "font-size": 11,
        "font-weight": 700,
        "text-wrap": "none",
        "text-max-width": 96,
        "text-valign": "center",
        "text-halign": "center",
        "text-outline-width": 0,
        "text-outline-opacity": 0,
        "min-zoomed-font-size": 9,
        width: 62,
        height: 62,
        "overlay-opacity": 0,
        "border-width": 0,
        "border-opacity": 0,
        "background-opacity": 0.97,
        "text-margin-y": 0,
      },
    },
    {
      selector: 'node[isTF = 1]',
      style: {
        shape: "diamond",
        "background-color": "#334155",
      },
    },
    {
      selector: 'node[isTF = 0]',
      style: {
        shape: "ellipse",
        "background-color": "#334155",
      },
    },
    {
      selector: "edge",
      style: {
        width: "mapData(visualScore, 0, 1, 1.4, 4.2)",
        "line-color": "data(edgeColor)",
        opacity: "mapData(visualScore, 0, 1, 0.55, 0.82)",
        "curve-style": "bezier",
        "source-endpoint": "outside-to-node",
        "source-distance-from-node": "data(sourceDistanceFromNode)",
        "target-endpoint": "outside-to-node",
        "target-distance-from-node": "data(targetDistanceFromNode)",
        "line-cap": "butt",
        "source-arrow-shape": "data(sourceArrowShape)",
        "source-arrow-color": "data(edgeColor)",
        "source-arrow-fill": "data(arrowFill)",
        "target-arrow-shape": "data(targetArrowShape)",
        "target-arrow-color": "data(edgeColor)",
        "target-arrow-fill": "data(arrowFill)",
        "arrow-scale": 0.9,
        "overlay-opacity": 0,
        "z-index": 1,
      },
    },
    {
      selector: "edge.reciprocal",
      style: {
        "curve-style": "unbundled-bezier",
        "control-point-distances": "data(controlPointDistance)",
        "control-point-weights": "data(controlPointWeight)",
      },
    },
    {
      selector: "node:selected",
      style: {
        "background-color": "#334155",
        "background-opacity": 1,
        "border-width": 3.5,
        "border-color": "#1b75a6",
        "border-opacity": 1,
        "underlay-color": "#1b75a6",
        "underlay-opacity": 0.18,
        "underlay-padding": 8,
        "z-index": 20,
      },
    },
    {
      selector: "node.selected-edge-endpoint:unselected",
      style: {
        "border-width": 3,
        "border-color": "#1b75a6",
        "border-opacity": 1,
        "underlay-color": "#1b75a6",
        "underlay-opacity": 0.12,
        "underlay-padding": 6,
        "z-index": 14,
      },
    },
    {
      selector: "edge:selected",
      style: {
        width: "mapData(visualScore, 0, 1, 3.4, 6.6)",
        "line-color": "#1b75a6",
        "source-arrow-shape": "data(sourceArrowShape)",
        "source-arrow-color": "#1b75a6",
        "source-arrow-fill": "data(arrowFill)",
        "target-arrow-shape": "data(targetArrowShape)",
        "target-arrow-color": "#1b75a6",
        "target-arrow-fill": "data(arrowFill)",
        "mid-target-arrow-shape": "none",
        "mid-target-arrow-color": "rgba(27, 117, 166, 0)",
        "arrow-scale": 1.22,
        opacity: 1,
        "line-cap": "butt",
        "z-index": 18,
        "underlay-color": "#9cc8df",
        "underlay-opacity": 0.24,
        "underlay-padding": 4,
      },
    },
    {
      selector: "edge.hovered:unselected",
      style: {
        width: "mapData(visualScore, 0, 1, 1.8, 4.8)",
        "line-color": "data(edgeColor)",
        "source-arrow-shape": "data(sourceArrowShape)",
        "source-arrow-color": "data(edgeColor)",
        "source-arrow-fill": "data(arrowFill)",
        "target-arrow-shape": "data(targetArrowShape)",
        "target-arrow-color": "data(edgeColor)",
        "target-arrow-fill": "data(arrowFill)",
        "mid-target-arrow-shape": "none",
        "mid-target-arrow-color": "rgba(213, 94, 0, 0)",
        "arrow-scale": 1.1,
        opacity: 1,
        "z-index": 11,
        "underlay-opacity": 0,
      },
    },
  ];
}
