input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/b6f385b3acd2/_beeline_runtime/pearson/inputs"
  datasets:
    - dataset_id: "b6f385b3acd2"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
  algorithms:
    - algorithm_id: "PEARSON"
      image: "local"
      should_run: [True]
      params:
        {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/b6f385b3acd2/_beeline_runtime/pearson/outputs"
