input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/ec559ba1b366/_beeline_runtime/SCODE/inputs"
  datasets:
    - dataset_id: "ec559ba1b366"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
          pseudoTimeData: "PseudoTime.csv"
  algorithms:
    - algorithm_id: "SCODE"
      image: "grnbeeline/scode:base"
      should_run: [True]
      params:
        z: [10]
        nIter: [1000]
        nRep: [6]
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/ec559ba1b366/_beeline_runtime/SCODE/outputs"
