input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/ec559ba1b366/_beeline_runtime/PEARSON/inputs"
  datasets:
    - dataset_id: "ec559ba1b366"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
          pseudoTimeData: "PseudoTime.csv"
  algorithms:
    - algorithm_id: "PEARSON"
      image: "local"
      should_run: [True]
      params:
        {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/ec559ba1b366/_beeline_runtime/PEARSON/outputs"
