input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/88efd32738f1/_beeline_runtime/GRNVBEM/inputs"
  datasets:
    - dataset_id: "88efd32738f1"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
          pseudoTimeData: "PseudoTime.csv"
  algorithms:
    - algorithm_id: "GRNVBEM"
      image: "grnbeeline/grnvbem:base"
      should_run: [True]
      params:
        {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/88efd32738f1/_beeline_runtime/GRNVBEM/outputs"
