input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/ec559ba1b366/_beeline_runtime/GRISLI/inputs"
  datasets:
    - dataset_id: "ec559ba1b366"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
          pseudoTimeData: "PseudoTime.csv"
  algorithms:
    - algorithm_id: "GRISLI"
      image: "grnbeeline/grisli:base"
      should_run: [True]
      params:
        L: [10]
        R: [3000]
        alphaMin: [0.0]
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/ec559ba1b366/_beeline_runtime/GRISLI/outputs"
