input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/7d4492f0513d/_beeline_runtime/grnboost2/inputs"
  datasets:
    - dataset_id: "7d4492f0513d"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
  algorithms:
    - algorithm_id: "GRNBOOST2"
      image: "grnbeeline/arboreto:base"
      should_run: [True]
      params:
        {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/7d4492f0513d/_beeline_runtime/grnboost2/outputs"
