input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/3f58617709c4/_beeline_runtime/grnboost2/inputs"
  datasets:
    - dataset_id: "3f58617709c4"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
  algorithms:
    - algorithm_id: "GRNBOOST2"
      image: "grnbeeline/arboreto:base"
      should_run: [True]
      params:
        {}
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/3f58617709c4/_beeline_runtime/grnboost2/outputs"
