input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/88efd32738f1/_beeline_runtime/LEAP/inputs"
  datasets:
    - dataset_id: "88efd32738f1"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
          pseudoTimeData: "PseudoTime.csv"
  algorithms:
    - algorithm_id: "LEAP"
      image: "grnbeeline/leap:base"
      should_run: [True]
      params:
        maxLag: [0.33]
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/88efd32738f1/_beeline_runtime/LEAP/outputs"
