input_settings:
  input_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/88efd32738f1/_beeline_runtime/SINGE/inputs"
  datasets:
    - dataset_id: "88efd32738f1"
      should_run: [True]
      runs:
        - run_id: "run-1"
          exprData: "ExpressionData.csv"
          pseudoTimeData: "PseudoTime.csv"
  algorithms:
    - algorithm_id: "SINGE"
      image: "grnbeeline/singe:0.4.1"
      should_run: [True]
      params:
        lambda: [0.01]
        dT: [15]
        num_lags: [5]
        kernel_width: [0.5]
        prob_zero_removal: [0]
        prob_remove_samples: [0.0]
        family: ["gaussian"]
        num_replicates: [6]
output_settings:
  output_dir: "/Users/molyloo/Documents/TRU/GRNScope/backend/projects/88efd32738f1/_beeline_runtime/SINGE/outputs"
